### ISSUE TITLE
Process restaurant categorical data into numerical data

### ISSUE THREAD

**Issue by iKevinY** [ubclaunchpad/yelp-challenge#3]
In its current form, the information in [`yelp_business.csv`](https://www.kaggle.com/yelp-dataset/yelp-dataset/version/4#yelp_business.csv) and [`yelp_business_attributes`](https://www.kaggle.com/yelp-dataset/yelp-dataset/version/4#yelp_business_attributes.csv) can't be fed directly into a model, since many of the columns contain data that isn't numerical (ie. easily put into a matrix).

Ideally, we want to concatenate rows from these two tables, strip out the unnecessary information (ie. street names), and post-process some other stuff (ie. encode boolean data as explicit 1s and 0s).

- [ ] Complete the implementation of [`clustering.preprocess.create_feature_matrix`](https://github.com/ubclaunchpad/yelp-challenge/blob/b17701325dbdda2d82dd9c9fe9b53457472c3c0c/clustering/preprocess.py#L26).

**Comment by miltonleung** [comment]
I added columns for specific restaurant categories, which is around 300. I chose to include the categories that have at least 8 restaurants in them. 

As for attributes, it appears most of the attributes are NA. 
For example, `Alcohol`
* NA 93%
* True 5%
* False 2%

If I added an `serves_alcohol` column, should I default the value to be false. Would this be making too many assumptions?

**Comment by iKevinY** [comment]
> If I added an `serves_alcohol` column, should I default the value to be false. Would this be making too many assumptions?

I think false-as-a-fallback is probably fine for now at least.

**Comment by miltonleung** [comment]
These are all the business attributes that have an significant response rating or one we deemed was important for clustering restaurants:

BusinessAcceptsCreditCards 84%
BusinessParking_garage 87%
BusinessParking_street 74%
BusinessParking_validated 74%
BusinessParking_lot 75%
BusinessParking_valet 74%
Alcohol: 93%
BikeParking: 74%
WheelchairAccessible: 86%
RestaurantsReservations: 98%
HappyHour: 96%
Caters 99%
DogsAllowed: 96%
HasTV: 98%
GoodForKids: 97%
OutdoorSeating 99%

**Comment by sarina-chen** [comment]
In addition to the above attributes, I also added the following attributes that are specific to restaurants:
RestaurantsPriceRange2,
RestaurantsAttire,
RestaurantsTakeOut,
RestaurantsDelivery

I found the percentage on kaggle is not that accurate, here's the percentage of 0/1 values for each of the attribute columns:

1    81.225404
0    18.774596
Name: BusinessAcceptsCreditCards, dtype: float64

1    72.703899
0    27.296101
Name: GoodForKids, dtype: float64

0    59.858675
1    40.141325
Name: HasTV, dtype: float64

1    50.644535
0    49.355465
Name: BikeParking, dtype: float64

0    63.979501
1    36.020499
Name: WheelchairAccessible, dtype: float64

0    66.048659
1    33.951341
Name: RestaurantsReservations, dtype: float64

0    91.226628
1     8.773372
Name: HappyHour, dtype: float64

0    67.755759
1    32.244241
Name: Caters, dtype: float64

0    97.539048
1     2.460952
Name: DogsAllowed, dtype: float64

0    67.62108
1    32.37892
Name: OutdoorSeating, dtype: float64

1    83.744075
0    16.255925
Name: RestaurantsTakeOut, dtype: float64

0    78.033337
1    21.966663
Name: RestaurantsDelivery, dtype: float64

0    89.117241
1    10.882759
Name: Alcohol_beer_and_wine, dtype: float64

0    70.288423
1    29.711577
Name: Alcohol_full_bar, dtype: float64

0    52.230948
1    47.769052
Name: RestaurantsPriceRange2_2, dtype: float64

0    64.262851
1    35.737149
Name: RestaurantsPriceRange2_1, dtype: float64

0    95.001137
1     4.998863
Name: RestaurantsPriceRange2_3, dtype: float64

0    99.107971
1     0.892029
Name: RestaurantsPriceRange2_4, dtype: float64

1    81.632939
0    18.367061
Name: RestaurantsAttire_casual, dtype: float64

0    97.61076
1     2.38924
Name: RestaurantsAttire_dressy, dtype: float64

0    99.779616
1     0.220384
Name: RestaurantsAttire_formal, dtype: float64

0    95.968377
1     4.031623
Name: BusinessParking_garage, dtype: float64

0    82.878282
1    17.121718
Name: BusinessParking_street, dtype: float64

0    99.475277
1     0.524723
Name: BusinessParking_validated, dtype: float64

0    66.676578
1    33.323422
Name: BusinessParking_lot, dtype: float64

0    97.992059
1     2.007941
Name: BusinessParking_valet, dtype: float64

**Comment by iKevinY** [comment]
Closed by @miltonleung and @sarina-chen in #12 (thank you)!
